### ISSUE TITLE
add warning in Chrome when using `file://`

### ISSUE THREAD

**Issue by notetiene** [udacity/frontend-grading-engine#29]
Previously, there was a warning in Chrome about using the extension with the `file://` scheme. Chrome doesn't support loading files from that scheme using `XMLHttpRequest`. Also, since the file input doesn't work anymore ( #21 ), it was a noisy warning I decided to remove.

Actually there may be a workaround by using the filesystem API, but injecting it might be much more complicated.

**Comment by notetiene** [comment]
This is now fixed in the Devel branch.

**Comment by Alleno** [comment]
This still appears to be a problem in the extension downloaded from chrome store. I've got it installed on ubuntu 16.04, and it doesn't seem to want to load tests from file. The two sample tests work though.
